### ISSUE TITLE
Node composition at PODM

### ISSUE THREAD

**Issue by Anil09cm** [01org/intelRSD#11]
Tried Node composition at PODM, Facing an issue here,

Node creation was successful when tried with JSON template containing only Processor Requirements.
But when the same Template along with Processor , Memory, Ethernet Interface and Local drive Requirements failed to compose node with following Error Message.

error" : {
    "code" : "Base.1.0.ResourcesStateMismatch",
    "message" : "Conflict during allocation",
    "@Message.ExtendedInfo" : [ {
      "Message" : "There are no computer systems available for this allocation request."
    }, {
      "Message" : "Available assets count after applying filters: [available: 9 -> status: 9 -> resource: 1 -> chassis: 1 -> processors: 1 -> memory: 0 -> local drives: 0 -> ethernet interfaces: 0]"
    } ]
  }

**Comment by maciejro** [comment]
Hi @Anil09cm,

Could you provide the allocation JSON for your second request with extended requirements for resources? We will analyze it and try to figure out what happened. If the request itself won’t be enough, we might ask you then for more data (e.g. the state of PODM REST API resources).

**Comment by Anil09cm** [comment]
I have tried the way you mentioned above. The result was same.
I am attaching .txt format of the json file which I used for this operation


[node.txt](https://github.com/01org/intelRSD/files/533169/node.txt)

**Comment by maciejro** [comment]
Hi @Anil09cm,

First of all, sorry for a delayed response. We've looked at your allocation JSON and found two possible causes of this allocation failure:

1. A typo in Memory Manufacturer property (the value typed is "Kinston" instead of the most probable "Kingston")
2. Specifying both “Resource” and “Chassis” properties that are not within the same physical hierarchy. When those two parameters are defined in a request it is necessary for the System that you intend to use (`/redfish/v1/Systems/1`) to be contained within the requested Chassis. Please check if you can navigate your way up to this Chassis resource using “Links -> Chassis” of this System and eventually navigate higher in Chassis hierarchy using “Links -> ContainedBy” in PODM REST API.

Please check if any of the above could be the cause of this allocation failure. If not – please send us PODM logs (`/var/log/pod-manager/pod-manager-application.log`) along with a dump of current state of PODM REST API.

**Comment by Anil09cm** [comment]
Hi @maciejro 

I have verified the Hierarchical relationships between Processor Chassis and all.
I tried composing the node but faced same issue.
I am attaching the which are  required for you.

[compose_node.txt](https://github.com/01org/intelRSD/files/536431/compose_node.txt)
[hierarchy.txt](https://github.com/01org/intelRSD/files/536432/hierarchy.txt)
[out_put.txt](https://github.com/01org/intelRSD/files/536433/out_put.txt)

**Comment by fberndl** [comment]
Hi @Anil09cm 

you still have "Manufacturer" set to "Kinston" in the latest attached files.

**Comment by maciejro** [comment]
Hi @Anil09cm,

We’ve looked at the dump of PODM REST API and compared it with your allocation JSON request. It looks like the Memory resource does not have _OperatingSpeedMHz_ property set with any value (in returned JSON for this resource you can find that `"OperatingSpeedMHz : null`). 
As you can see in [Predicates class for Memory allocation at line #42](https://github.com/01org/intelRSD/blob/master/PODM/SW/pod-manager/podm-assembly/src/main/java/com/intel/podm/allocation/mappers/memory/Predicates.java#L42) the value _SpeedMHz_ is compared with mentioned property and as result, in your case, the value `false` will be returned causing your allocation request to fail. 

Here are proposed solutions:
1. Please make sure that PSME is presenting such value on its REST API and use it in allocation JSON sent to PODM.
2. Omit other properties for Memory resource in allocation JSON, because specific Memory resource is given in “Resource” object. If you provide this URI  in request, all other properties will be validated against that specific resource (so no matching will be executed against all available Memory). 

If it’s still not the case, could you change logger level to `DEBUG`? Please go to `/opt/pod-manager/wildfly/standalone/configuration/logback.xml` and change following line
`<logger name="com.intel" level="INFO" additivity="false" >`
to
`<logger name="com.intel" level="DEBUG" additivity="false" >`
and then send us once again `/var/log/pod-manager/pod-manager-application.log`?

**Comment by Anil09cm** [comment]
Hi @maciejro,

I have followed your instructions. Now its working.
Thanks for the valuable inputs.
