### ISSUE TITLE
[PSME] Configuration file "bdc_r_configuration.json" is missing or postint is outdated

### ISSUE THREAD

**Issue by fberndl** [01org/intelRSD#14]
Hi,

the file bdc_r_configuration.json is missing in this repository, it exists in the v1.1 repository which is outdated. Some postint refeer to this file. Can you clarify if I can use the file from the v1.1 version or if the postinst files are not up to date. 

https://github.com/01org/intelRSD/PSME/agent-intel/packages/DEB/psme-compute-intel/DEBIAN/postinst

**Comment by maciejro** [comment]
Hi @fberndl,

Sorry once again for long response time. The creation of debian package for `psme-compute-intel` is a leftover from old release - it will not work with currently available source code and will be removed in next release. 
Sorry of inconvience.

**Comment by fberndl** [comment]
Hi @maciejro,

so I should only use the packages and  binaries?? of `psme-compute` and not of  `psme-compute-intel `? 
When I use psme-compute the psme-rest-server throws an ERROR `application-ref/src/rest-ref/model/handlers/handler_manager.cpp:handle:262]Update event for unknown entry. Ignoring`

**Comment by maciejro** [comment]
Hi @fberndl,

Please have in mind that code available on this repository is only reference code that can be used to build custom RSD solution. Agents included in `agent-stubs` and `agent-simulator` directories and `psme-rest-server` agent do not require actual HW support. Other agents are required to support specific GAMI commands for specific HW (more information can be found in [Intel® Rack Scale Design GAMI API Specification](http://www.intel.com/content/www/us/en/architecture-and-technology/rack-scale-design/gami-api-specification.html))

Files provided for creating OS-specific packages are just an example of how the process shall look like. Developers should tailor this process to fit their custom PSME code. It’s recommended to build binaries for PSME in this repository rather than RPM/DEB packages.




> When I use psme-compute the psme-rest-server throws an ERROR application-ref/src/rest-ref/model/handlers/handler_manager.cpp:handle:262]Update event for unknown entry. Ignoring

Concerning the error message that you encountered – it informs that event received by PSME REST Server was not recognized so no further steps will be taken.

> Regarding those two binaries, maybe you can tell me what the SDV abbreviation stands for?

*SDV* stands for Software Development Vehicle. That means the platform that was used by Intel while creating this reference code. „

**Comment by fberndl** [comment]
Hi @maciejro,

> Files provided for creating OS-specific packages are just an example of how the process shall look like. 
That is what I have assumed, I just wanted to be sure. 

> SDV stands for Software Development Vehicle. That means the platform that was used by Intel while creating this reference code. 

Was this the Bulldog Creek Hardware or which other hardware is psme-compute-intel compatible? 


 In my opinion the difference between  psme-compute and psme-compute-intel should be described in the psme-user-guide, the` psme-compute-intel ` is not described. So in the `software-reference-kit-started-guide.pdf` at the examples there should be stated to use Dell PowerEdge in combination with psme-compute and the reference hardware from intel (bulldog creek?) with psme-compute-intel. 

Thanks for answering a lot of my questions , I just want to assure that we understand the software reference kit before we start to developing our solution on it.

**Comment by maciejro** [comment]
Hi @fberndl,

> Was this the Bulldog Creek Hardware or which other hardware is psme-compute-intel compatible?

That's correct. SDV for this reference code is Bulldog Creek as mentioned in [Intel® Rack Scale Design PSME API Specification](http://www.intel.com/content/www/us/en/architecture-and-technology/rack-scale-design/psme-api-specification.html).


> In my opinion the difference between psme-compute and psme-compute-intel should be described in the psme-user-guide, thepsme-compute-intel is not described. So in the software-reference-kit-started-guide.pdf at the examples there should be stated to use Dell PowerEdge in combination with psme-compute and the reference hardware from intel (bulldog creek?) with psme-compute-intel.

Thank you for the information. In next release we will update RSD documents about all available agents in solution.

> Thanks for answering a lot of my questions , I just want to assure that we understand the software reference kit before we start to developing our solution on it.

You're welcome!
