### ISSUE TITLE
[PSME] 2 memory leaks

### ISSUE THREAD

**Issue by zhlicen** [01org/intelRSD#18]
1. [logger](https://github.com/01org/intelRSD/blob/master/PSME/common/logger/src/logger.c#L126)
"msg" should be freed at the end of this function.

2. [make_uuid](https://github.com/01org/intelRSD/blob/master/PSME/common/agent-framework/src/module-ref/model/resource.cpp#L40)
"char*" returned from _id.string()_ should be freed manually.

**Comment by tbykowsk** [comment]
Hi @zhlicen,

Thank you for your message.
I confirm the second issue, it will be fixed in the next release.

In the first issue "msg" is processed in a separate thread and freed by [logger_stream_add_message](https://github.com/01org/intelRSD/blob/master/PSME/common/logger/src/logger_stream.c#L280) function.

**Comment by zhlicen** [comment]
@tbykowsk Thank you for your reply, I misunderstood on the first issue.

**Comment by tbykowsk** [comment]
You are most welcome @zhlicen, we appreciate your input.
Please feel free to ask any follow-up questions or you could close the issue.
