### ISSUE TITLE
wildfly fail to start normally

### ISSUE THREAD

**Issue by Vishesh-GIT** [01org/intelRSD#23]
Hi,
i am trying to install PODM and seeing warning when wildfly is started as below
root@DCE-DV:/home/admin# service wildfly start
 * Starting WildFly Application Server wildfly                                                                                                   [ OK ]
 * WildFly Application Server hasn't started within the timeout allowed
 * please review file "/var/log/wildfly/console.log" to see the status of the service

i checked "/var/log/wildfly/console.log" which states that "Could not start http listener". i have attached the full log file here. 

[wildfly-console.txt](https://github.com/01org/intelRSD/files/868309/wildfly-console.txt)

in some wildfly forum, there was suggestion to change the port numbers. i have tried those option also but still same problem persist. please let me know anything you can make out from the log file.

Thanks

**Comment by maciejro** [comment]
Hi @Vishesh-GIT,

The most common reason for this issue is using IPv6 stack instead of IPv4. Wildfly uses IPv4 stack by default. For more detailed information about forcing JVM & Wildfly using proper IP stack, please follow official [Wildfly 9 documentation about Interfaces and ports](https://docs.jboss.org/author/display/WFLY9/Interfaces+and+ports) and go to _IPv4 versus IPv6_ chapter. 

As this problem is connected to 3rd party software, not related to RSD software, I'm closing this issue.
